# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bero.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bero.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbero.proto\x12\x04\x62\x65ro\"#\n\x0fNavigateRequest\x12\x10\n\x08waypoint\x18\x01 \x01(\t\"4\n\x10NavigateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0cSceneRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"5\n\rSceneResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2\x86\x01\n\x0fRobotController\x12\x39\n\x08Navigate\x12\x15.bero.NavigateRequest\x1a\x16.bero.NavigateResponse\x12\x38\n\rDescribeScene\x12\x12.bero.SceneRequest\x1a\x13.bero.SceneResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bero_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVIGATEREQUEST']._serialized_start=20
  _globals['_NAVIGATEREQUEST']._serialized_end=55
  _globals['_NAVIGATERESPONSE']._serialized_start=57
  _globals['_NAVIGATERESPONSE']._serialized_end=109
  _globals['_SCENEREQUEST']._serialized_start=111
  _globals['_SCENEREQUEST']._serialized_end=141
  _globals['_SCENERESPONSE']._serialized_start=143
  _globals['_SCENERESPONSE']._serialized_end=196
  _globals['_ROBOTCONTROLLER']._serialized_start=199
  _globals['_ROBOTCONTROLLER']._serialized_end=333
# @@protoc_insertion_point(module_scope)
